# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '02.The Movies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 02.The Movies
  pod 'Alamofire', '~> 5.4'
  pod 'Wormholy', :configurations => ['Debug']
  pod 'SDWebImage', '~> 5.0'
  pod 'YouTubePlayer'
  pod 'RealmSwift', '~>10'
end
